<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-02 at 18:56:46.
 */
class NewGenLibTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var NewGenLib
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new NewGenLib;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers NewGenLib::getHolding
     * @todo   Implement testGetHolding().
     */
    public function testGetHolding()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NewGenLib::getMyFines
     * @todo   Implement testGetMyFines().
     */
    public function testGetMyFines()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NewGenLib::getMyHolds
     * @todo   Implement testGetMyHolds().
     */
    public function testGetMyHolds()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NewGenLib::getMyProfile
     * @todo   Implement testGetMyProfile().
     */
    public function testGetMyProfile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NewGenLib::getMyTransactions
     * @todo   Implement testGetMyTransactions().
     */
    public function testGetMyTransactions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NewGenLib::getStatus
     * @todo   Implement testGetStatus().
     */
    public function testGetStatus()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NewGenLib::getStatuses
     * @todo   Implement testGetStatuses().
     */
    public function testGetStatuses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NewGenLib::patronLogin
     * @todo   Implement testPatronLogin().
     */
    public function testPatronLogin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NewGenLib::getNewItems
     * @todo   Implement testGetNewItems().
     */
    public function testGetNewItems()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NewGenLib::getPurchaseHistory
     * @todo   Implement testGetPurchaseHistory().
     */
    public function testGetPurchaseHistory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
