<?php /* Smarty version 2.6.19, created on 2012-06-18 13:11:54
         compiled from MyResearch/checkedout.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'MyResearch/checkedout.tpl', 6, false),array('modifier', 'escape', 'MyResearch/checkedout.tpl', 11, false),array('modifier', 'trim', 'MyResearch/checkedout.tpl', 15, false),array('modifier', 'lower', 'MyResearch/checkedout.tpl', 29, false),array('modifier', 'regex_replace', 'MyResearch/checkedout.tpl', 29, false),)), $this); ?>
<?php echo '<div data-role="page" id="MyResearch-checkedout">'; ?><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "header.tpl", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php echo '<div data-role="content">'; ?><?php if ($this->_tpl_vars['user']->cat_username): ?><?php echo '<h3>'; ?><?php echo translate(array('text' => 'Your Checked Out Items'), $this);?><?php echo '</h3>'; ?><?php if ($this->_tpl_vars['transList']): ?><?php echo '<ul class="results checkedout-list" data-role="listview">'; ?><?php $_from = $this->_tpl_vars['transList']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }$this->_foreach['recordLoop'] = array('total' => count($_from), 'iteration' => 0);
if ($this->_foreach['recordLoop']['total'] > 0):
    foreach ($_from as $this->_tpl_vars['resource']):
        $this->_foreach['recordLoop']['iteration']++;
?><?php echo '<li>'; ?><?php if (! empty ( $this->_tpl_vars['resource']['id'] )): ?><?php echo '<a rel="external" href="'; ?><?php echo $this->_tpl_vars['path']; ?><?php echo '/Record/'; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['resource']['id'])) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?><?php echo '">'; ?><?php endif; ?><?php echo '<div class="result">'; ?><?php echo ''; ?><?php if (! empty ( $this->_tpl_vars['resource']['id'] )): ?><?php echo '<h3>'; ?><?php echo ((is_array($_tmp=((is_array($_tmp=$this->_tpl_vars['resource']['title'])) ? $this->_run_mod_handler('trim', true, $_tmp, '/:') : trim($_tmp, '/:')))) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?><?php echo '</h3>'; ?><?php echo ''; ?><?php elseif (! empty ( $this->_tpl_vars['resource']['title'] )): ?><?php echo '<h3>'; ?><?php echo ((is_array($_tmp=((is_array($_tmp=$this->_tpl_vars['resource']['title'])) ? $this->_run_mod_handler('trim', true, $_tmp, '/:') : trim($_tmp, '/:')))) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?><?php echo '</h3>'; ?><?php echo ''; ?><?php else: ?><?php echo '<h3>'; ?><?php echo translate(array('text' => 'Title not available'), $this);?><?php echo '</h3>'; ?><?php endif; ?><?php echo ''; ?><?php if (! empty ( $this->_tpl_vars['resource']['author'] )): ?><?php echo '<p>'; ?><?php echo translate(array('text' => 'by'), $this);?><?php echo ' '; ?><?php echo $this->_tpl_vars['resource']['author']; ?><?php echo '</p>'; ?><?php endif; ?><?php echo ''; ?><?php if (! empty ( $this->_tpl_vars['resource']['format'] )): ?><?php echo '<p>'; ?><?php $_from = $this->_tpl_vars['resource']['format']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['format']):
?><?php echo '<span class="iconlabel '; ?><?php echo ((is_array($_tmp=((is_array($_tmp=$this->_tpl_vars['format'])) ? $this->_run_mod_handler('lower', true, $_tmp) : smarty_modifier_lower($_tmp)))) ? $this->_run_mod_handler('regex_replace', true, $_tmp, "/[^a-z0-9]/", "") : smarty_modifier_regex_replace($_tmp, "/[^a-z0-9]/", "")); ?><?php echo '">'; ?><?php echo translate(array('text' => $this->_tpl_vars['format']), $this);?><?php echo '</span>'; ?><?php endforeach; endif; unset($_from); ?><?php echo '</p>'; ?><?php endif; ?><?php echo '<p><strong>'; ?><?php echo translate(array('text' => 'Due'), $this);?><?php echo '</strong>: '; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['resource']['duedate'])) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?><?php echo '</p>'; ?><?php if ($this->_tpl_vars['resource']['renewMessage']): ?><?php echo '<p class=\''; ?><?php if ($this->_tpl_vars['resource']['renewResult'] == true): ?><?php echo 'renewPassed'; ?><?php else: ?><?php echo 'renewFailed'; ?><?php endif; ?><?php echo '\'>'; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['resource']['renewMessage'])) ? $this->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp)); ?><?php echo '</p>'; ?><?php endif; ?><?php echo '</div>'; ?><?php if (! empty ( $this->_tpl_vars['resource']['id'] )): ?><?php echo '</a>'; ?><?php endif; ?><?php echo '<a href="'; ?><?php echo $this->_tpl_vars['path']; ?><?php echo '/MyResearch/Renew?itemId='; ?><?php echo $this->_tpl_vars['resource']['itemid']; ?><?php echo '&itemIndex='; ?><?php echo $this->_tpl_vars['resource']['itemindex']; ?><?php echo '" data-role="button" rel="external" data-icon="refresh">Renew Item</a></li>'; ?><?php endforeach; endif; unset($_from); ?><?php echo '</ul>'; ?><?php else: ?><?php echo '<p>'; ?><?php echo translate(array('text' => 'You do not have any items checked out'), $this);?><?php echo '.</p>'; ?><?php endif; ?><?php echo ''; ?><?php else: ?><?php echo 'You must login to view this information. Click <a href="'; ?><?php echo $this->_tpl_vars['path']; ?><?php echo '/MyResearch/Login">here</a> to login.'; ?><?php endif; ?><?php echo '</div>'; ?><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "footer.tpl", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php echo '</div>'; ?>