<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-02 at 18:56:53.
 */
class VirtuaTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Virtua
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Virtua;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Virtua::getStatus
     * @todo   Implement testGetStatus().
     */
    public function testGetStatus()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Virtua::getStatuses
     * @todo   Implement testGetStatuses().
     */
    public function testGetStatuses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Virtua::getHolding
     * @todo   Implement testGetHolding().
     */
    public function testGetHolding()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Virtua::getPurchaseHistory
     * @todo   Implement testGetPurchaseHistory().
     */
    public function testGetPurchaseHistory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Virtua::getAll853
     * @todo   Implement testGetAll853().
     */
    public function testGetAll853()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Virtua::patronLogin
     * @todo   Implement testPatronLogin().
     */
    public function testPatronLogin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Virtua::getMyProfile
     * @todo   Implement testGetMyProfile().
     */
    public function testGetMyProfile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Virtua::getMyFines
     * @todo   Implement testGetMyFines().
     */
    public function testGetMyFines()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Virtua::getMyHolds
     * @todo   Implement testGetMyHolds().
     */
    public function testGetMyHolds()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Virtua::getMyTransactions
     * @todo   Implement testGetMyTransactions().
     */
    public function testGetMyTransactions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Virtua::getCourses
     * @todo   Implement testGetCourses().
     */
    public function testGetCourses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Virtua::findReserves
     * @todo   Implement testFindReserves().
     */
    public function testFindReserves()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Virtua::getOpeningHours
     * @todo   Implement testGetOpeningHours().
     */
    public function testGetOpeningHours()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Virtua::placeHold
     * @todo   Implement testPlaceHold().
     */
    public function testPlaceHold()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Virtua::cancelHold
     * @todo   Implement testCancelHold().
     */
    public function testCancelHold()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Virtua::renewItems
     * @todo   Implement testRenewItems().
     */
    public function testRenewItems()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
