<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-02 at 18:56:58.
 */
class CatalogConnectionTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var CatalogConnection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CatalogConnection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers CatalogConnection::checkFunction
     * @todo   Implement testCheckFunction().
     */
    public function testCheckFunction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CatalogConnection::getHoldsMode
     * @todo   Implement testGetHoldsMode().
     */
    public function testGetHoldsMode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CatalogConnection::getStatus
     * @todo   Implement testGetStatus().
     */
    public function testGetStatus()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CatalogConnection::getStatuses
     * @todo   Implement testGetStatuses().
     */
    public function testGetStatuses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CatalogConnection::getHolding
     * @todo   Implement testGetHolding().
     */
    public function testGetHolding()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CatalogConnection::getPurchaseHistory
     * @todo   Implement testGetPurchaseHistory().
     */
    public function testGetPurchaseHistory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CatalogConnection::patronLogin
     * @todo   Implement testPatronLogin().
     */
    public function testPatronLogin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CatalogConnection::getMyTransactions
     * @todo   Implement testGetMyTransactions().
     */
    public function testGetMyTransactions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CatalogConnection::getMyFines
     * @todo   Implement testGetMyFines().
     */
    public function testGetMyFines()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CatalogConnection::getReadingHistory
     * @todo   Implement testGetReadingHistory().
     */
    public function testGetReadingHistory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CatalogConnection::doReadingHistoryAction
     * @todo   Implement testDoReadingHistoryAction().
     */
    public function testDoReadingHistoryAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CatalogConnection::getMyHolds
     * @todo   Implement testGetMyHolds().
     */
    public function testGetMyHolds()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CatalogConnection::getMyProfile
     * @todo   Implement testGetMyProfile().
     */
    public function testGetMyProfile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CatalogConnection::placeHold
     * @todo   Implement testPlaceHold().
     */
    public function testPlaceHold()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CatalogConnection::placeItemHold
     * @todo   Implement testPlaceItemHold().
     */
    public function testPlaceItemHold()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CatalogConnection::getHoldLink
     * @todo   Implement testGetHoldLink().
     */
    public function testGetHoldLink()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CatalogConnection::updatePatronInfo
     * @todo   Implement testUpdatePatronInfo().
     */
    public function testUpdatePatronInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CatalogConnection::selfRegister
     * @todo   Implement testSelfRegister().
     */
    public function testSelfRegister()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CatalogConnection::getNewItems
     * @todo   Implement testGetNewItems().
     */
    public function testGetNewItems()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CatalogConnection::getFunds
     * @todo   Implement testGetFunds().
     */
    public function testGetFunds()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CatalogConnection::getDepartments
     * @todo   Implement testGetDepartments().
     */
    public function testGetDepartments()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CatalogConnection::getInstructors
     * @todo   Implement testGetInstructors().
     */
    public function testGetInstructors()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CatalogConnection::getCourses
     * @todo   Implement testGetCourses().
     */
    public function testGetCourses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CatalogConnection::findReserves
     * @todo   Implement testFindReserves().
     */
    public function testFindReserves()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CatalogConnection::getSuppressedRecords
     * @todo   Implement testGetSuppressedRecords().
     */
    public function testGetSuppressedRecords()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CatalogConnection::__call
     * @todo   Implement test__call().
     */
    public function test__call()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
