<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-02 at 18:56:57.
 */
class PHPExcelTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var PHPExcel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PHPExcel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers PHPExcel::disconnectWorksheets
     * @todo   Implement testDisconnectWorksheets().
     */
    public function testDisconnectWorksheets()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::getProperties
     * @todo   Implement testGetProperties().
     */
    public function testGetProperties()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::setProperties
     * @todo   Implement testSetProperties().
     */
    public function testSetProperties()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::getSecurity
     * @todo   Implement testGetSecurity().
     */
    public function testGetSecurity()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::setSecurity
     * @todo   Implement testSetSecurity().
     */
    public function testSetSecurity()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::getActiveSheet
     * @todo   Implement testGetActiveSheet().
     */
    public function testGetActiveSheet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::createSheet
     * @todo   Implement testCreateSheet().
     */
    public function testCreateSheet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::addSheet
     * @todo   Implement testAddSheet().
     */
    public function testAddSheet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::removeSheetByIndex
     * @todo   Implement testRemoveSheetByIndex().
     */
    public function testRemoveSheetByIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::getSheet
     * @todo   Implement testGetSheet().
     */
    public function testGetSheet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::getAllSheets
     * @todo   Implement testGetAllSheets().
     */
    public function testGetAllSheets()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::getSheetByName
     * @todo   Implement testGetSheetByName().
     */
    public function testGetSheetByName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::getIndex
     * @todo   Implement testGetIndex().
     */
    public function testGetIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::setIndexByName
     * @todo   Implement testSetIndexByName().
     */
    public function testSetIndexByName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::getSheetCount
     * @todo   Implement testGetSheetCount().
     */
    public function testGetSheetCount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::getActiveSheetIndex
     * @todo   Implement testGetActiveSheetIndex().
     */
    public function testGetActiveSheetIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::setActiveSheetIndex
     * @todo   Implement testSetActiveSheetIndex().
     */
    public function testSetActiveSheetIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::setActiveSheetIndexByName
     * @todo   Implement testSetActiveSheetIndexByName().
     */
    public function testSetActiveSheetIndexByName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::getSheetNames
     * @todo   Implement testGetSheetNames().
     */
    public function testGetSheetNames()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::addExternalSheet
     * @todo   Implement testAddExternalSheet().
     */
    public function testAddExternalSheet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::getNamedRanges
     * @todo   Implement testGetNamedRanges().
     */
    public function testGetNamedRanges()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::addNamedRange
     * @todo   Implement testAddNamedRange().
     */
    public function testAddNamedRange()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::getNamedRange
     * @todo   Implement testGetNamedRange().
     */
    public function testGetNamedRange()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::removeNamedRange
     * @todo   Implement testRemoveNamedRange().
     */
    public function testRemoveNamedRange()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::getWorksheetIterator
     * @todo   Implement testGetWorksheetIterator().
     */
    public function testGetWorksheetIterator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::copy
     * @todo   Implement testCopy().
     */
    public function testCopy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::__clone
     * @todo   Implement test__clone().
     */
    public function test__clone()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::getCellXfCollection
     * @todo   Implement testGetCellXfCollection().
     */
    public function testGetCellXfCollection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::getCellXfByIndex
     * @todo   Implement testGetCellXfByIndex().
     */
    public function testGetCellXfByIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::getCellXfByHashCode
     * @todo   Implement testGetCellXfByHashCode().
     */
    public function testGetCellXfByHashCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::getDefaultStyle
     * @todo   Implement testGetDefaultStyle().
     */
    public function testGetDefaultStyle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::addCellXf
     * @todo   Implement testAddCellXf().
     */
    public function testAddCellXf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::removeCellXfByIndex
     * @todo   Implement testRemoveCellXfByIndex().
     */
    public function testRemoveCellXfByIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::getCellXfSupervisor
     * @todo   Implement testGetCellXfSupervisor().
     */
    public function testGetCellXfSupervisor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::getCellStyleXfCollection
     * @todo   Implement testGetCellStyleXfCollection().
     */
    public function testGetCellStyleXfCollection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::getCellStyleXfByIndex
     * @todo   Implement testGetCellStyleXfByIndex().
     */
    public function testGetCellStyleXfByIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::getCellStyleXfByHashCode
     * @todo   Implement testGetCellStyleXfByHashCode().
     */
    public function testGetCellStyleXfByHashCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::addCellStyleXf
     * @todo   Implement testAddCellStyleXf().
     */
    public function testAddCellStyleXf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::removeCellStyleXfByIndex
     * @todo   Implement testRemoveCellStyleXfByIndex().
     */
    public function testRemoveCellStyleXfByIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPExcel::garbageCollect
     * @todo   Implement testGarbageCollect().
     */
    public function testGarbageCollect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
