<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-02 at 18:57:06.
 */
class ConnectionManagerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ConnectionManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ConnectionManager;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ConnectionManager::connectToCatalog
     * @todo   Implement testConnectToCatalog().
     */
    public function testConnectToCatalog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConnectionManager::connectToDatabase
     * @todo   Implement testConnectToDatabase().
     */
    public function testConnectToDatabase()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConnectionManager::connectToIndex
     * @todo   Implement testConnectToIndex().
     */
    public function testConnectToIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
