<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-02 at 18:56:59.
 */
class ISBNTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ISBN
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ISBN;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ISBN::get10
     * @todo   Implement testGet10().
     */
    public function testGet10()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ISBN::get13
     * @todo   Implement testGet13().
     */
    public function testGet13()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ISBN::isValid
     * @todo   Implement testIsValid().
     */
    public function testIsValid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ISBN::normalizeISBN
     * @todo   Implement testNormalizeISBN().
     */
    public function testNormalizeISBN()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ISBN::getISBN10CheckDigit
     * @todo   Implement testGetISBN10CheckDigit().
     */
    public function testGetISBN10CheckDigit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ISBN::isValidISBN10
     * @todo   Implement testIsValidISBN10().
     */
    public function testIsValidISBN10()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ISBN::getISBN13CheckDigit
     * @todo   Implement testGetISBN13CheckDigit().
     */
    public function testGetISBN13CheckDigit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ISBN::isValidISBN13
     * @todo   Implement testIsValidISBN13().
     */
    public function testIsValidISBN13()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
