<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-02 at 18:57:02.
 */
class sip2Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var sip2
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new sip2;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers sip2::msgPatronStatusRequest
     * @todo   Implement testMsgPatronStatusRequest().
     */
    public function testMsgPatronStatusRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::msgCheckout
     * @todo   Implement testMsgCheckout().
     */
    public function testMsgCheckout()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::msgCheckin
     * @todo   Implement testMsgCheckin().
     */
    public function testMsgCheckin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::msgBlockPatron
     * @todo   Implement testMsgBlockPatron().
     */
    public function testMsgBlockPatron()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::msgSCStatus
     * @todo   Implement testMsgSCStatus().
     */
    public function testMsgSCStatus()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::msgRequestACSResend
     * @todo   Implement testMsgRequestACSResend().
     */
    public function testMsgRequestACSResend()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::msgLogin
     * @todo   Implement testMsgLogin().
     */
    public function testMsgLogin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::msgPatronInformation
     * @todo   Implement testMsgPatronInformation().
     */
    public function testMsgPatronInformation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::msgEndPatronSession
     * @todo   Implement testMsgEndPatronSession().
     */
    public function testMsgEndPatronSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::msgFeePaid
     * @todo   Implement testMsgFeePaid().
     */
    public function testMsgFeePaid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::msgItemInformation
     * @todo   Implement testMsgItemInformation().
     */
    public function testMsgItemInformation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::msgItemStatus
     * @todo   Implement testMsgItemStatus().
     */
    public function testMsgItemStatus()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::msgPatronEnable
     * @todo   Implement testMsgPatronEnable().
     */
    public function testMsgPatronEnable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::msgHold
     * @todo   Implement testMsgHold().
     */
    public function testMsgHold()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::msgRenew
     * @todo   Implement testMsgRenew().
     */
    public function testMsgRenew()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::msgRenewAll
     * @todo   Implement testMsgRenewAll().
     */
    public function testMsgRenewAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::parsePatronStatusResponse
     * @todo   Implement testParsePatronStatusResponse().
     */
    public function testParsePatronStatusResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::parseCheckoutResponse
     * @todo   Implement testParseCheckoutResponse().
     */
    public function testParseCheckoutResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::parseCheckinResponse
     * @todo   Implement testParseCheckinResponse().
     */
    public function testParseCheckinResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::parseACSStatusResponse
     * @todo   Implement testParseACSStatusResponse().
     */
    public function testParseACSStatusResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::parseLoginResponse
     * @todo   Implement testParseLoginResponse().
     */
    public function testParseLoginResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::parsePatronInfoResponse
     * @todo   Implement testParsePatronInfoResponse().
     */
    public function testParsePatronInfoResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::parseEndSessionResponse
     * @todo   Implement testParseEndSessionResponse().
     */
    public function testParseEndSessionResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::parseFeePaidResponse
     * @todo   Implement testParseFeePaidResponse().
     */
    public function testParseFeePaidResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::parseItemInfoResponse
     * @todo   Implement testParseItemInfoResponse().
     */
    public function testParseItemInfoResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::parseItemStatusResponse
     * @todo   Implement testParseItemStatusResponse().
     */
    public function testParseItemStatusResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::parsePatronEnableResponse
     * @todo   Implement testParsePatronEnableResponse().
     */
    public function testParsePatronEnableResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::parseHoldResponse
     * @todo   Implement testParseHoldResponse().
     */
    public function testParseHoldResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::parseRenewResponse
     * @todo   Implement testParseRenewResponse().
     */
    public function testParseRenewResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::parseRenewAllResponse
     * @todo   Implement testParseRenewAllResponse().
     */
    public function testParseRenewAllResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::get_message
     * @todo   Implement testGet_message().
     */
    public function testGet_message()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::connect
     * @todo   Implement testConnect().
     */
    public function testConnect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::disconnect
     * @todo   Implement testDisconnect().
     */
    public function testDisconnect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::_datestamp
     * @todo   Implement test_datestamp().
     */
    public function test_datestamp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::_parsevariabledata
     * @todo   Implement test_parsevariabledata().
     */
    public function test_parsevariabledata()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::_crc
     * @todo   Implement test_crc().
     */
    public function test_crc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::_getseqnum
     * @todo   Implement test_getseqnum().
     */
    public function test_getseqnum()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::_debugmsg
     * @todo   Implement test_debugmsg().
     */
    public function test_debugmsg()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::_check_crc
     * @todo   Implement test_check_crc().
     */
    public function test_check_crc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::_newMessage
     * @todo   Implement test_newMessage().
     */
    public function test_newMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::_addFixedOption
     * @todo   Implement test_addFixedOption().
     */
    public function test_addFixedOption()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::_addVarOption
     * @todo   Implement test_addVarOption().
     */
    public function test_addVarOption()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers sip2::_returnMessage
     * @todo   Implement test_returnMessage().
     */
    public function test_returnMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
