<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-02 at 18:57:02.
 */
class WorldCatUtilsTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var WorldCatUtils
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new WorldCatUtils;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers WorldCatUtils::getXISBN
     * @todo   Implement testGetXISBN().
     */
    public function testGetXISBN()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WorldCatUtils::getXISSN
     * @todo   Implement testGetXISSN().
     */
    public function testGetXISSN()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WorldCatUtils::isUsefulNameChunk
     * @todo   Implement testIsUsefulNameChunk().
     */
    public function testIsUsefulNameChunk()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WorldCatUtils::getRelatedIdentities
     * @todo   Implement testGetRelatedIdentities().
     */
    public function testGetRelatedIdentities()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WorldCatUtils::getRelatedTerms
     * @todo   Implement testGetRelatedTerms().
     */
    public function testGetRelatedTerms()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
