<?php /* Smarty version 2.6.19, created on 2012-06-19 13:41:24
         compiled from Admin/listWidgets.tpl */ ?>
<?php echo '<div id="page-content" class="content">'; ?><?php if ($this->_tpl_vars['error']): ?><?php echo '<p class="error">'; ?><?php echo $this->_tpl_vars['error']; ?><?php echo '</p>'; ?><?php endif; ?><?php echo '<div id="sidebar">'; ?><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "MyResearch/menu.tpl", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php echo ''; ?><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "Admin/menu.tpl", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php echo '</div><div id="main-content"><h1>Available List Widgets</h1><div id="widgets"></div>'; ?><?php echo '<div id="availableWidgets"><table><thead><tr><th>Name</th><th>Description</th><th>Actions</th></tr></thead><tbody>'; ?><?php $_from = $this->_tpl_vars['availableWidgets']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['id'] => $this->_tpl_vars['widget']):
?><?php echo '<tr><td>'; ?><?php echo $this->_tpl_vars['widget']->name; ?><?php echo '</td><td>'; ?><?php echo $this->_tpl_vars['widget']->description; ?><?php echo '</td><td><a class="button" href="'; ?><?php echo $this->_tpl_vars['path']; ?><?php echo '/Admin/ListWidgets?objectAction=view&id='; ?><?php echo $this->_tpl_vars['widget']->id; ?><?php echo '"/>View</a><a class="button" href="'; ?><?php echo $this->_tpl_vars['path']; ?><?php echo '/Admin/ListWidgets?objectAction=edit&id='; ?><?php echo $this->_tpl_vars['widget']->id; ?><?php echo '"/>Edit</a><a class="button" href="'; ?><?php echo $this->_tpl_vars['path']; ?><?php echo '/API/SearchAPI?method=getListWidget&id='; ?><?php echo $this->_tpl_vars['widget']->id; ?><?php echo '"/>Preview</a><a class="button" href="'; ?><?php echo $this->_tpl_vars['path']; ?><?php echo '/Admin/ListWidgets?objectAction=delete&id='; ?><?php echo $this->_tpl_vars['widget']->id; ?><?php echo '" onclick="return confirm(\'Are you sure you want to delete '; ?><?php echo $this->_tpl_vars['widget']->name; ?><?php echo '?\');"/>Delete</a></td>'; ?><?php endforeach; endif; unset($_from); ?><?php echo '</tbody></table><input type="button" class="button" name="addWidget" value="Add Widget" onclick="window.location = \''; ?><?php echo $this->_tpl_vars['path']; ?><?php echo '/Admin/ListWidgets?objectAction=add\';"/></div></div></div>'; ?>